version: '3.8'

services:
  app:
    build: .
    container_name: uber-like-app
    ports: 
     - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
  postgres:
   image: postgres:15
   container_name: uber-postgres
   env_file:
   - .env
   ports: 
   - "5432:5432"
   volumes:
   - pgdata:/var/lib/postgresql/data
   restart: unless-stopped

  redis:
    image: redis:7
    container_name: uber-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata:
