DROP TABLE IF EXISTS trips;

CREATE TABLE trips (id SERIAL PRIMARY KEY, rider_id INT NOT NULL , driver_id INT NOT NULL, location TEXT NOT NULL, ETA REAL CHECK(ETA>= 0), status VARCHAR(50) CHECK(status IN  ('PENDING', 'ACCEPTED', 'RUNNING', 'FINISHED', 'CANCELLED')),
CONSTRAINT fk_rider FOREIGN KEY (rider_id) REFERENCES riders(id) ON DELETE CASCADE,
CONSTRAINT fk_driver FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE SET NULL
 );