
CREATE TABLE drivers (id SERIAL PRIMARY KEY,username VARCHAR(50) NOT NULL,email  VARCHAR(50) UNIQUE,photo VARCHAR(200) NOT NULL, phone VARCHAR(20) NOT NULL, vehicle_type VARCHAR(50) NOT NULL, vehicle_name VARCHAR(50) NOT NULL, vehicle_no  VARCHAR(10) UNIQUE NOT NULL, password VARCHAR(200) NOT NULL);
